---
stages:
- name: AllInStage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: BuildJob
    type: builder
    script: |
      #!/bin/bash
      echo "Testing"
